version: '3.8'

services:
  # Application Spring Boot
  app:
    build: .
    container_name: tresorie-app
    ports:
      - "8080:8080"
    volumes:
      # On relie le dossier ./data du projet au dossier /app/data du conteneur Docker
      - "./data:/app/data"
