spring.application.name=tresorie

spring.datasource.url=jdbc:h2:file:./data/tresorie_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Indispensable pour Spring Boot 2.7 avec H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Active la console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Clé API Gemini - injectée via variable d'environnement (ne JAMAIS mettre en dur !)
gemini.api.key=${GEMINI_API_KEY:}

